Models/Edu.cs
namespace mvc_test.Models
{
	public class Edu
	{
		public required string name { get; set; }
		public int startDate { get; set; }
		public int? endDate { get; set; }
		public float? GPA { get; set; }
		public string? major { get; set; }

	}
}

Models/ErrorViewModel.cs
namespace mvc_test.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/IncomeModel.cs
namespace mvc_test.Models
{
    public class IncomeModel
    {
        public float YearlyWage { get; set; }
        public float IncomeTax {  get; set; } 
        public IncomeModel(float i)
        {
            YearlyWage = i;
            IncomeTax = i > 30000 ? i / 5 : 0;          
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using mvc_test.Models;
using System.Diagnostics;


namespace mvc_test.Controllers
{

    public class HomeController : Controller
    {


        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public List<List<Edu>> All = [
            [
            new (){name = "N158 Public School", startDate = 2012, endDate = 2015},
            new (){name = "N30 Public School", startDate = 2015, endDate = 2017},
            new (){name = "N63 Public School", startDate = 2017, endDate = 2024},
            new (){name = "University of Georgia", startDate = 2024, endDate = null, GPA = (float?)3.25, major = "Informatics" },
            ],
			[
			new (){name = "Bincom Volunteer Program", startDate = 2025}
			]
			];

		public IActionResult Index()
        {
            return View(All);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Controllers/IncomeController.cs
using Microsoft.AspNetCore.Mvc;
using mvc_test.Models;
namespace mvc_test.Controllers
{
	public class IncomeController : Controller
	{
		public IActionResult Index(float i)
		{
			IncomeModel Icm = new IncomeModel(i * 12);
			return View(Icm);
		}

	}
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "My CV";
    float income = 0;

    DateTime zeroTime = new DateTime(1, 1, 1);
    DateTime today = DateTime.Today;
    DateTime birthday = new DateTime(2007, 3, 22, 12, 0, 0);
    TimeSpan span = today - birthday;
    int years = (zeroTime + span).Year - 1;

}
<link rel="stylesheet" href="./css/site.css" />

<div>
    
    <div class="edu-flex-container">
        <h1 style="text-align: center; 
            margin-left: 25vw;
        margin-right: 5vw;
            width: 50vw;
        text-align: center" 
        class="display-4">
            My CV
        </h1>

        <img src="~/Images/1728397222705.jpg" style="width: 10vw; height: 12vw; 
        margin-left: 10%;
    margin-right: 10%;
        float: right;
    position: relative" />
    </div>
    
    <div>
        <h2 style="text-align: center" class="display-4">Background</h2>
       </div>
       <p style="width: 80vw">
           My name is Saba. I am a @years year old software developer from
        <a href="https://en.wikipedia.org/wiki/Georgia_(country)">Georgia.</a>
        I began learning coding in 2024 with Python but have shifted to using languages like C++; JavaScript and C#.

       </p>
       <br />
    <h2 style="text-align: center" class="display-4">Education</h2>
    @foreach(Edu school in Model[0])
    {
        <div style="text-align: center">
            <p style="font-weight: bold">@school.startDate - @school.endDate</p>
            <p>@school.name</p>
            @if(school.GPA != null)
            {
                <p>GPA: @school.GPA / 4.00</p>
            }
            @if(school.major != null)
            {
                <p>Major: @school.major</p>
            }
        </div>
    }
    
    <div style="text-align: center">
        <h2  class="display-4">Work experience</h2>
        @foreach(Edu work in Model[1])
        {
            <p style="font-weight: bold">@work.startDate - @work.endDate</p>
            <p>@work.name</p>
        }
    </div>
    
    <div style="text-align: center">
        <h2 class="display-4">DEMO: Calculate your income tax</h2>
        <p> Based on Georgia tax code</p>
        @using(Html.BeginForm("Index", "Income")){
            <input type="number" name="i"/> 
            <button type="submit" style="border: 0px"> submit </button><br />
            <span>Note: Please enter monthly wage </span>

        }
    </div>
    <br />
</div>

Views/Income/Index.cshtml
@{
	float income = @Model.YearlyWage;
	float tax = @Model.IncomeTax;
}
<div style="text-align: center">
	<h1 style="font-weight: bold" class="display-4">Your Taxes</h1>
	<br/>

	@if(income >= 30000)
	{
		<p  class="display-4">
			You owe @tax GEL.
		</p>
	}
	@if(income < 30000)
	{
		<p  class="display-4">
			Your income is less than 30000 GEL per year, meaning you owe 0.
		</p>
	}
	@using (Html.BeginForm("Index", "Home"))
	{
		<button style="border: 0px;
			background-image:
				linear-gradient(135deg, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.05))">
			Back to Homepage
		</button>
	}

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc_test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvc_test.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Saba Imnadze</a>
                
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style=" position: relative;
   <!-- background: linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5)); -->
    height: 130%; margin-bottom: 0vh" class="border-top footer text-muted">
        <div class="container">
           links: <br />
           <div style="display: flex; flex-direction: row; justify-content: space-evenly">
               <a style="color: gray" href="https://github.com/saba-24">GitHub</a>
               <a style="color: gray" href="https://www.linkedin.com/in/saba-imnadze-475a03331/">LinkedIn</a>
           </div>
        </div>
    </footer> 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>